# Generated by Django 3.2.8 on 2021-10-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
